name: Muse Photo
favicon: null
layout_spectrum: 0.46146
typography_spectrum: 0.4421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#404040'
    - '#7a7a7a'
    - '#c9c9c9'
    - '#232323'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
