name: Muse Photo
favicon: null
layout_spectrum: 0.75742
typography_spectrum: 0.73358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#525252'
    - '#7c7c7c'
    - '#d8d8d8'
    - '#0b0b0b'
    - '#e77ed0'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
