layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3405018
  brandStrength: 0.625
  lightness: 0.6326165
  brandColors:
    - '#525252'
    - '#7c7c7c'
    - '#d8d8d8'
    - '#0b0b0b'
    - '#e77ed0'
  rhythmicContrast: 0.75
typography_spectrum: 0.7401434
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Muse Photo
