name: Muse Photo
favicon: null
layout_spectrum: 0.75518
typography_spectrum: 0.4421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#174306'
    - '#bfabd4'
    - '#ebefee'
    - '#509e4f'
    - '#d40f5e'
  brandStrength: 0.18346001184545457
  lightness: 0.5080301300622523
  saturation: 0.21249894937500358
  rhythmicContrast: 0.25
purpose: []
