name: Muse Photo
favicon: null
layout_spectrum: 0.75518
typography_spectrum: 0.4421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3cfca'
    - '#919191'
    - '#0b0a06'
    - '#655b59'
    - '#4a1c17'
  brandStrength: 0.18346001184545457
  lightness: 0.5080301300622523
  saturation: 0.21249894937500358
  rhythmicContrast: 0.25
purpose: []
